apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
        version: one
    spec:
      containers:
      - name: hello-node
        image: muellermich/hello-node:v1
        ports:
        - containerPort: 8080
